#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Lambo Console', 0.1);

$app->add(new Laravel\Installer\Console\NewCommand);
$app->add(new CreateCommand);

$app->run();
